# Generated by Django 4.2 on 2025-06-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField()),
                ('arrive_time', models.TimeField()),
                ('arrive_at', models.CharField(choices=[('Seoul', '서울'), ('Yongsan', '용산')], max_length=10)),
                ('train_type', models.CharField(choices=[('KTX', 'KTX'), ('MUGUNGHWA', '무궁화'), ('ITX-maeum', 'ITX-마음'), ('I-Saemaeul', 'I-새마을')], max_length=20)),
                ('platform', models.CharField(choices=[('6', 6), ('7', 7), ('8', 8), ('9', 9)], max_length=5)),
            ],
        ),
    ]
