# Generated by Django 4.2 on 2025-06-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainTT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20)),
                ('train_type', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('platform', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
